# Generated by Django 3.0.3 on 2020-03-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0003_auto_20200307_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='comments_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
