# Generated by Django 3.0.3 on 2020-03-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0008_image_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password1', models.CharField(max_length=20)),
                ('password2', models.CharField(max_length=20)),
            ],
        ),
    ]
